const PDFDocument = require('pdfkit');

// Generate Salary Slip PDF
exports.generateSalarySlipPDF = (salaryData, res) => {
  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-disposition', `attachment; filename="Salary_Slip_${salaryData.month}_${salaryData.year}.pdf"`);
  res.setHeader('Content-type', 'application/pdf');
  doc.pipe(res);

  doc.fontSize(20).text('Quaid-e-Millat Public Boys High School', { align: 'center' });
  doc.moveDown();
  doc.fontSize(16).text('Salary Slip', { align: 'center', underline: true });
  doc.moveDown();

  doc.fontSize(12);
  doc.text(`Employee Name: ${salaryData.employee?.name || 'N/A'}`);
  doc.text(`Role: ${salaryData.employeeType}`);
  doc.text(`Month/Year: ${salaryData.month} ${salaryData.year}`);
  doc.text(`Working Days: ${salaryData.workingDays}`);
  doc.text(`Present Days: ${salaryData.presentDays}`);
  doc.moveDown();

  doc.text(`Base Salary: Rs ${salaryData.baseSalary}`);
  doc.text(`Allowances: Rs ${salaryData.allowances || 0}`);
  doc.text(`Deductions: Rs ${salaryData.deductions || 0}`);
  doc.moveDown();
  
  doc.fontSize(14).text(`Net Salary: Rs ${salaryData.netSalary}`, { underline: true });
  
  doc.moveDown(2);
  doc.fontSize(10).text(`Generated by: ${salaryData.generatedBy?.name || 'System'}`);
  doc.text(`Date: ${new Date().toLocaleDateString()}`);
  
  doc.end();
};

// Generate Report Card PDF
exports.generateReportCardPDF = (resultData, res) => {
  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-disposition', `attachment; filename="Report_Card_${resultData.student?.rollNumber || 'Result'}.pdf"`);
  res.setHeader('Content-type', 'application/pdf');
  doc.pipe(res);

  doc.fontSize(20).text('Quaid-e-Millat Public Boys High School', { align: 'center' });
  doc.moveDown();
  doc.fontSize(16).text('Report Card', { align: 'center', underline: true });
  doc.moveDown();

  doc.fontSize(12);
  doc.text(`Student Name: ${resultData.student?.firstName} ${resultData.student?.lastName}`);
  doc.text(`Roll Number: ${resultData.student?.rollNumber}`);
  doc.text(`Class: ${resultData.class?.name || 'N/A'} - Section: ${resultData.section || 'N/A'}`);
  doc.text(`Exam Type: ${resultData.examType}`);
  doc.text(`Exam Date: ${resultData.examDate ? new Date(resultData.examDate).toLocaleDateString() : 'N/A'}`);
  doc.moveDown();

  doc.fontSize(14).text('Subjects:', { underline: true });
  doc.fontSize(12);
  doc.moveDown(0.5);

  resultData.subjects.forEach(sub => {
    doc.text(`${sub.name}: ${sub.obtainedMarks} / ${sub.totalMarks}`);
  });

  doc.moveDown();
  doc.fontSize(14).text(`Total Marks: ${resultData.obtainedMarks} / ${resultData.totalMarks}`);
  doc.text(`Percentage: ${resultData.percentage}%`);
  doc.text(`Grade: ${resultData.grade}`);
  doc.text(`Status: ${resultData.status?.toUpperCase()}`);
  if (resultData.classPosition) {
    doc.text(`Position: ${resultData.classPosition}`);
  }
  
  doc.moveDown(2);
  doc.fontSize(10).text(`Generated on: ${new Date().toLocaleDateString()}`);
  
  doc.end();
};
